### PR TITLE
S3 buckets

### PR DESCRIPTION
**Pull request by Skarlso**
Hi.

Added s3 to the list of services and a README update to include that S3 needs CORS configured on the bucket for it to work.

### CODE REVIEW

**Comment by kesor** [comment]
@Skarlso pretty sure that calling the S3 API does not require to change your bucket(s) to enable CORS. The CORS on buckets is for the web serving functionality.

**Comment by Skarlso** [comment]
Unfortunately if it's not set, than you'll get this:

```
index.html#:1 Failed to load https://s3.us-west-1.amazonaws.com/: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access. The response had HTTP status code 403.
```

That said now, even if I do configure everything it still doesn't work properly. :/ S3 just isn't working man. Damn it. I'll close the pull.

**Comment by Skarlso** [comment]
S3 is a special case which I think is just not working through the browser properly right now.

BTW. Awesome stuff! :) 👍

**Comment by kesor** [comment]
Although S3 is supposed to have CORS according to https://github.com/aws/aws-sdk-js/blob/master/SERVICES.md

It does look like unfortunately, it doesn't work at the moment. Maybe someone from AWS will pick this up and fix it :/

**Comment by Skarlso** [comment]
Yep. :-( I even manipulated the request object and set some headers up before sending. Still didn't work. :-(

**Pull request closed without merging**
